vert-x3/vertx-mongo-client

vertx-mongo-client/src/main/asciidoc/groovy/index.adoc
vertx-mongo-client/src/main/asciidoc/java/index.adoc
vertx-mongo-client/src/main/asciidoc/js/index.adoc
vertx-mongo-client/src/main/asciidoc/ruby/index.adoc
vertx-mongo-client/src/main/groovy/io/vertx/groovy/ext/mongo/MongoClient.groovy
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/codec/VertxCodecRegistry.java
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/codec/json/JsonObjectCodec.java
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/config/MongoClientOptionsParser.java
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/package-info.java
vertx-mongo-client/src/test/java/io/vertx/ext/mongo/MongoClientTestBase.java
vertx-mongo-client/src/test/java/io/vertx/ext/mongo/MongoClientWithObjectIdTest.java
vertx-mongo-client/src/test/java/io/vertx/ext/mongo/impl/codec/json/JsonObjectCodecTest.java

Fixed issue 36 to add support for useObjectId in the configuration. If set to true, the _id field will be saved as an ObjectId in native MongoDB format. When read, it will be returned to the reader as a hex string rather than a compound $oid field. If the _id is set by the user prior to insert, it should be as a valid hex string.
I suggest merging sooner rather than later. It's a fairly core change and should be tested well prior to release in 3.1 I'm using the 3.1 SNAPSHOT with this change in an important project and it seems to be fine so far.

added support for useObjectId

---

vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/codec/json/AbstractJsonCodec.java
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/codec/json/JsonObjectCodec.java
vertx-mongo-client/src/test/java/io/vertx/ext/mongo/MongoClientTestBase.java
vertx-mongo-client/src/test/java/io/vertx/ext/mongo/MongoClientWithObjectIdTest.java
vertx-mongo-client/src/test/java/io/vertx/ext/mongo/impl/codec/json/AbstractJsonCodecTest.java
vertx-mongo-client/src/test/java/io/vertx/ext/mongo/impl/codec/json/JsonObjectCodecTest.java

Improve the ObjectId support in read/write object id from JsonObject. Also it adds protection if the "_id" field provided is not a valid ObjectId string.

Improve ObjectId support

---

vertx-mongo-client/src/main/java/examples/Examples.java
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/MongoClient.java
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/package-info.java
vertx-mongo-client/src/test/java/io/vertx/ext/mongo/MongoClientTestBase.java
vertx-mongo-service/src/main/java/io/vertx/ext/mongo/MongoService.java
vertx-mongo-service/src/main/java/io/vertx/ext/mongo/impl/MongoServiceImpl.java

Hello, 
This PR extends find method with batch cursor (cf. issue #33), avoiding acumulation of all results in a list and memory problems with not so huge collections. 
I uses it in another projet to pump a complete mongo collections like this:
```
FindOptions options = new FindOptions();
mongoClient.findBatchWithOptions("Articles", new JsonObject(), options, result -> {
vertx.eventBus().send(MLVerticle.ML_RECEIVER_ADD, result.result());
});
```
It push on event bus a complete collection of 100000 docs without problem.

Added new find method with batchCursor

---

vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/codec/json/JsonObjectCodec.java
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/config/CredentialListParser.java
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/config/WriteConcernParser.java

This pull request is focused on resolving occurrences of Sonar rules
squid:S134 - Control flow statements "if", "for", "while", "switch" and "try" should not be nested too deeply.
squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding.
squid:CommentedOutCodeLine - Sections of code should not be "commented out".
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S134
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck
https://dev.eclipse.org/sonar/rules/show/squid:CommentedOutCodeLine
Please let me know if you have any questions.
George Kankava

Multiple code improvements - squid:S134, squid:UselessParenthesesCheck, squid:CommentedOutCodeLine

---

vertx-mongo-client/pom.xml

Added bnd plugin to generate OSGi manifest. Test cases available here: https://github.com/paulbakker/vertx-osgi-testcases
Note that this requires the unreleased bnd-maven-plugin 3.2.

bnd config to generate OSGi manifest

---

vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/config/WriteConcernParser.java
vertx-mongo-client/src/test/java/io/vertx/ext/mongo/impl/codec/json/JsonObjectCodecTest.java

This pull request is focused on resolving occurrences of Sonar rules
squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding.
squid:S1226 - Method parameters, caught exceptions and foreach variables should not be reassigned.
squid:LowerCaseLongSuffixCheck - Long suffix "L" should be upper case.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck
https://dev.eclipse.org/sonar/rules/show/squid:S1226
https://dev.eclipse.org/sonar/rules/show/squid:LowerCaseLongSuffixCheck
Please let me know if you have any questions.
George Kankava

Multiple code improvements - squid:UselessParenthesesCheck, squid:S1226, squid:LowerCaseLongSuffixCheck

---

vertx-mongo-client/pom.xml

Again, revert this, the plugin is not yet released.
Reverts vert-x3/vertx-mongo-client#74

Revert "Revert "bnd config to generate OSGi manifest""

---

vertx-mongo-client/pom.xml
vertx-mongo-service/pom.xml

The bnd-maven-plugin 3.2.0 is just released. This PR adds the plugin to generate OSGi metadata.

added just released bnd maven plugin 3.2.0

---

vertx-mongo-client/src/main/asciidoc/dataobjects.adoc
vertx-mongo-client/src/main/asciidoc/groovy/index.adoc
vertx-mongo-client/src/main/asciidoc/java/index.adoc
vertx-mongo-client/src/main/asciidoc/js/index.adoc
vertx-mongo-client/src/main/asciidoc/ruby/index.adoc
vertx-mongo-client/src/main/generated/io/vertx/rxjava/ext/mongo/MongoClient.java
vertx-mongo-client/src/main/groovy/io/vertx/groovy/ext/mongo/MongoClient.groovy
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/MongoClient.java
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/UpdateOptions.java
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java
vertx-mongo-client/src/main/resources/vertx-mongo-js/mongo_client.js
vertx-mongo-client/src/main/resources/vertx-mongo/mongo_client.rb
vertx-mongo-client/src/test/java/io/vertx/ext/mongo/MongoClientTestBase.java
vertx-mongo-service/src/main/generated/io/vertx/ext/mongo/MongoServiceVertxEBProxy.java
vertx-mongo-service/src/main/generated/io/vertx/ext/mongo/MongoServiceVertxProxyHandler.java
vertx-mongo-service/src/main/generated/io/vertx/rxjava/ext/mongo/MongoService.java
vertx-mongo-service/src/main/groovy/io/vertx/groovy/ext/mongo/MongoService.groovy
vertx-mongo-service/src/main/java/io/vertx/ext/mongo/MongoService.java
vertx-mongo-service/src/main/java/io/vertx/ext/mongo/impl/MongoServiceImpl.java
vertx-mongo-service/src/main/resources/vertx-mongo-js/mongo_service.js
vertx-mongo-service/src/main/resources/vertx-mongo/mongo_service.rb

support findOneAndX #82
Wrap findOneAndUpdate, findOneAndReplace and findOneAndDelete with corresponding "WithOptions" alternatives.
This is mostly the same code for those three mongo calls, can you rename the issue to reflect this PR?

support findOneAndX

---

vertx-mongo-client/src/main/asciidoc/groovy/index.adoc
vertx-mongo-client/src/main/asciidoc/java/index.adoc
vertx-mongo-client/src/main/asciidoc/js/index.adoc
vertx-mongo-client/src/main/asciidoc/ruby/index.adoc
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/config/ClusterSettingsParser.java
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/package-info.java
vertx-mongo-client/src/test/java/io/vertx/ext/mongo/impl/config/ClusterSettingsParserTest.java

Allow configuration of the serverSelectionTimeout. This is currently not exposed in the vertx-mongo-client.

add serverSelectionTimeout to ClusterSettingsParser

---

vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/codec/json/JsonObjectCodec.java
vertx-mongo-client/src/test/java/io/vertx/ext/mongo/impl/codec/json/JsonObjectCodecTest.java

Extend $binary to handle optional $type field. If $type is not defined use default BsonBinarySubType.BINARY.

binary extended json format with type definition

---

vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/config/ClusterSettingsParser.java
vertx-mongo-client/src/test/java/io/vertx/ext/mongo/impl/config/ClusterSettingsParserTest.java

Fix issue reported at:
https://github.com/vert-x3/issues/issues/287
ClusterSettings.maxWaitQueueSize has been set to the same value as ConnectionPoolSettings.maxWaitQueueSize. From the mongo docs:
```
ClusterSettings.maxWaitQueueSize: This is the maximum number of concurrent operations allowed to wait for a server to become available. All further operations will get an exception immediately
```
```
ConnectionPoolSettings.maxWaitQueueSize: This is the maximum number of operations that may be waiting for a connection to become available from the pool. All further operations will get an exception immediately.
```
I would guess people would want these to be the same value, if we want them as different values I will change the config value.

Fix ClusterSettings.maxWaitQueueSize not being set

---

vertx-mongo-client/src/main/asciidoc/dataobjects.adoc
vertx-mongo-client/src/main/asciidoc/groovy/index.adoc
vertx-mongo-client/src/main/asciidoc/java/index.adoc
vertx-mongo-client/src/main/asciidoc/js/index.adoc
vertx-mongo-client/src/main/asciidoc/kotlin/index.adoc
vertx-mongo-client/src/main/asciidoc/ruby/index.adoc
vertx-mongo-client/src/main/generated/io/vertx/ext/mongo/FindOptionsConverter.java
vertx-mongo-client/src/main/java/examples/Examples.java
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/FindOptions.java
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/MongoClient.java
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/package-info.java
vertx-mongo-client/src/main/kotlin/io/vertx/kotlin/ext/mongo/FindOptions.kt
vertx-mongo-client/src/test/java/io/vertx/ext/mongo/DistinctTest.java
vertx-mongo-client/src/test/java/io/vertx/ext/mongo/FindOptionsTest.java
vertx-mongo-client/src/test/java/io/vertx/ext/mongo/MongoClientTest.java
vertx-mongo-service/src/main/java/io/vertx/ext/mongo/MongoService.java
vertx-mongo-service/src/main/java/io/vertx/ext/mongo/impl/MongoServiceImpl.java

Fixes #110 
The `xxxBatch` methods implementation use async result handlers incorrectly: such handlers should be called just once.
Instead, they should return a `ReadStream`, which brings:
- backpressure support
- RxJava support (via `ReadStream.toFlowable`)
Note that `MongoService` cannot implement them since `ReadStream` are not supported in service proxies.

RxJava support for batching methods

---

vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/config/MongoClientOptionsParser.java
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/config/SSLSettingsParser.java
vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/config/StreamTypeParser.java
vertx-mongo-client/src/test/java/io/vertx/ext/mongo/impl/config/ParsingSSLOptionsTest.java
vertx-mongo-client/src/test/java/io/vertx/ext/mongo/impl/config/ParsingStreamTypeTest.java

During the process of securing the traffic between existing mongodb cluster and the client, it is useful to use `sslInvalidHostNameAllowed ` for a while, during the transition period.
However, it seems like the driver completely ignores that connection string property.
It also ignores `streamType` and according to https://github.com/vert-x3/vertx-mongo-client/issues/1, the only way to use netty is to set `System.setProperty("org.mongodb.async.type", "netty");` which is now deprecated.
This PR adds support for both of these properties.
Oh and btw: i feel it would be much easier to either drop the 'JsonObject' configuration altogether or at least allow to rely only on connectionString and pass it to underlying mongo driver factory as it is

Improve ssl support

---

src/main/asciidoc/dataobjects.adoc
src/main/generated/io/vertx/ext/mongo/AggregateOptionsConverter.java
src/main/java/io/vertx/ext/mongo/AggregateOptions.java
src/main/java/io/vertx/ext/mongo/MongoClient.java
src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java
src/main/kotlin/io/vertx/kotlin/ext/mongo/AggregateOptions.kt
src/test/java/io/vertx/ext/mongo/AggregateOptionsTest.java
src/test/java/io/vertx/ext/mongo/MongoClientTest.java

As stated in https://github.com/vert-x3/vertx-mongo-client/issues/148 MongoDB has changed the handling of the aggregate command.
Would be great if you could have a look into it and tell me if you need something more to get this into the vertx-mongo-client.

aggregate support for mongo 3.6

---

src/main/java/io/vertx/ext/mongo/IndexOptions.java
src/test/java/io/vertx/ext/mongo/IndexOptionsTest.java

Add `equals` & `hashCode` methods to `IndexOptions`. Same semantics & style as in the other `*Options` objects.

add equals & hashCode to IndexOptions

---

src/main/java/io/vertx/ext/mongo/BulkWriteOptions.java
src/test/java/io/vertx/ext/mongo/BulkWriteOptionsTest.java

Add `equals` & `hashCode` methods to `BulkWriteOptions`. Same semantics & style as in the other `*Options` objects.

add equals & hashCode to BulkWriteOptions

---

src/main/java/io/vertx/ext/mongo/BulkOperation.java
src/test/java/io/vertx/ext/mongo/BulkOperationTest.java

Add `equals` & `hashCode` methods to `BulkOperation`. Same semantics & style as in the other objects. And same motivation as in PR #168 and #169.

add equals & hashCode to BulkOperation

---

src/main/java/io/vertx/ext/mongo/impl/config/SSLSettingsParser.java
src/test/java/io/vertx/ext/mongo/impl/config/ParsingSSLOptionsTest.java

add a vertx compatible option to trust all certificates setting an empty trust store in the ssl context

add trustAll and caPath option

---

src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java
src/test/java/io/vertx/ext/mongo/MongoClientTest.java

fix for the following behavior
when `findBatchWithOptions` is piped to a slow WriteStream or delayed on purpose via `pause`/`resume` or `fetch`, the stream calls the endHandler already after getting an empty result from the database but ignores the fact that the `InboundBuffer` still holds some elements

fix MongoIterableStream

---

src/main/asciidoc/dataobjects.adoc
src/main/generated/io/vertx/ext/mongo/AggregateOptionsConverter.java
src/main/java/io/vertx/ext/mongo/AggregateOptions.java
src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java
src/test/java/io/vertx/ext/mongo/AggregateOptionsTest.java
src/test/java/io/vertx/ext/mongo/GridFsTest.java
src/test/java/io/vertx/ext/mongo/MongoClientTest.java

When we manually use asynBatchCursor, we can't set awaitMaxTimeMs. Delete this posibility from out mongoClient. Maybe we should implement it in out layer.
https://github.com/vert-x3/vertx-mongo-client/issues/195

Fix mistake with maxAwaitTimeMs fix #195

---

src/main/asciidoc/index.adoc
src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java
src/main/java/io/vertx/ext/mongo/impl/config/CredentialListParser.java
src/main/java/io/vertx/ext/mongo/impl/config/MongoClientOptionsParser.java
src/main/java/io/vertx/ext/mongo/impl/config/SSLSettingsParser.java
src/test/java/io/vertx/ext/mongo/impl/config/CredentialListParserTest.java
src/test/java/io/vertx/ext/mongo/impl/config/MongoClientOptionsParserTest.java
src/test/java/io/vertx/ext/mongo/impl/config/ParsingReadConcernLevelTest.java
src/test/java/io/vertx/ext/mongo/impl/config/ParsingSSLOptionsTest.java
src/test/java/io/vertx/ext/mongo/impl/config/ParsingStreamTypeTest.java

* update credential option parser to support x509 without username
* refactor caPath to support certificate chains as well
* add keyPath and certPath
* refactor ssl impl to use vertx ssl helpers
* update docs and tests

add client certificate authentication

---

pom.xml
src/test/java/io/vertx/ext/mongo/MongoClientTest.java
src/test/java/io/vertx/ext/mongo/MongoClientTestBase.java
src/test/java/io/vertx/ext/mongo/MongoTestBase.java

Motivation:
* mongo 4.4.0 was released and needs driver 4.1.x for compatibility
* mongo mock still used 3.4 server version which is really old
upgrade to mongo 4.4.0 was not possible as this mongo mock does only support <4.0.x

upgrade mongo driver to 4.1.0, upgrade mongo mock to use 4.0.x

---

src/main/java/io/vertx/ext/mongo/IndexModel.java
src/test/java/io/vertx/ext/mongo/IndexModelTest.java

Add `equals` & `hashCode` methods to `IndexModel`. Same reasoning as for #168 and #169.

add equals & hashCode to IndexModel

---

src/main/java/io/vertx/ext/mongo/impl/config/SSLSettingsParser.java
src/test/java/io/vertx/ext/mongo/impl/config/ParsingSSLOptionsTest.java

When `ssl` is set to `true` but `caPath` is *not* set, a TrustManager with an empty KeyStore is created which causes the driver to fail when creating SSL connections because it doesn't trust *anybody*:
```
java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:101)
at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)
at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:309)
at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:183)
at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:255)
at …
```

SSL: Use default trust for empty trust options

---

src/main/asciidoc/index.adoc

Motivation:
Just read the official documentation and noticed that the dependend driver was referenced wrong. Since we are not using only the Vert.x MongoClient, it had some impact for me. I try to fix that trivial issue so others are not confused.

update reference link

---

src/main/asciidoc/dataobjects.adoc
src/main/generated/io/vertx/ext/mongo/IndexModelConverter.java
src/main/java/io/vertx/ext/mongo/IndexModel.java
src/test/java/io/vertx/ext/mongo/MongoClientTestBase.java

Converting an `IndexModel` from and to json is not fully implemented, the `IndexOptions` are ignored. This PR fixes this by using a generated `IndexModelConverter`.

fix from/to json of IndexModel

---

src/main/java/io/vertx/ext/mongo/impl/config/CredentialListParser.java
src/main/java/io/vertx/ext/mongo/impl/config/MongoClientOptionsParser.java
src/test/java/io/vertx/ext/mongo/impl/config/CredentialListParserTest.java

Motivation:
Tried to use vertx-mongo-client with a connectionString. Noticed that username and password are not used from connectionstring. See also issue 248:
https://github.com/vert-x3/vertx-mongo-client/issues/248
Conformance:
Should be conform

add ConnectionString to CredentialListParser

---

pom.xml
src/test/java/io/vertx/ext/mongo/MongoTestBase.java

Motivation:
As part of issue #236 : replace flapdoodle with testcontainers in order to be able to use a more recent version of MongoDB (> 4.0).

replaced flapdoodle with testcontainers (task related to the #236 issue)

---

src/main/asciidoc/index.adoc
src/main/generated/io/vertx/ext/mongo/FindOptionsConverter.java
src/main/java/io/vertx/ext/mongo/FindOptions.java
src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java

Vertx mongo client doesn't support the hint() helper method and we need it to optimize our queries by using specific index.

Add hint support for search request

---

pom.xml
src/test/java/io/vertx/ext/mongo/MongoClientTest.java
src/test/java/io/vertx/ext/mongo/MongoClientTestBase.java
src/test/java/io/vertx/ext/mongo/MongoTestBase.java

The (legacy async) Mongo Java driver being used has been updated to the
latest version of the 3.x branch.
The test cases have been updated to be able to run them successfully
with Mongo DB 3.5 and 3.6 instead of 3.4 only. The Mongo DB version used
for running the tests has been updated to 3.6.
The flapdoodle library which is used to start an embedded Mongo DB
server to run the test cases against has also been updated to a more
recent version.

[#259] Update Java driver to version 3.12.8

---

README.adoc
pom.xml
src/main/generated/io/vertx/ext/mongo/FindOptionsConverter.java
src/main/java/io/vertx/ext/mongo/BulkOperation.java
src/main/java/io/vertx/ext/mongo/FindOptions.java
src/main/java/io/vertx/ext/mongo/UpdateOptions.java
src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java
src/test/java/io/vertx/ext/mongo/BulkOperationTest.java
src/test/java/io/vertx/ext/mongo/UpdateOptionsTest.java

I encountered an inefficient collection index selection in a bulk update operation in MongoDB by default. The only way to change the index selection is to specify a `hint` in UpdateOptions.
The changes provided by this PR:
- Add hint support for all bulk operations and other methods with `UpdateOptions`.
- Remove broken links to documentation in `README.adoc`
- Remove `slf4j-api` dependency due to comment.
- Update `testcontainers` version to latest (1.15.2 is incompatible with a M1 chip)

Add hint support to Bulk operations 

---

src/main/java/io/vertx/ext/mongo/BulkOperation.java

Motivation:
This allows caller to send an empty JsonObject and later set only the needed fields and leave others at default.
Fix #280

Fix #280: Avoid NullPointerException in BulkOperation Constructor

---

src/main/asciidoc/index.adoc
src/test/java/io/vertx/ext/mongo/CompressorsConnectivityTest.java
src/test/java/io/vertx/ext/mongo/impl/config/CompressorsSettingsParserTest.java
src/test/java/io/vertx/ext/mongo/impl/config/MongoClientOptionsParserTest.java

Motivation:
Fix #296: Compressors config didn't work
Conformance:
Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

Fix #296 Compressors config didn't work

---

src/main/java/io/vertx/ext/mongo/MongoClient.java
src/main/java/io/vertx/ext/mongo/MongoGridFsClient.java
src/main/java/io/vertx/ext/mongo/package-info.java

Motivation:
Callback-based methods are deprecated in vert.x 5
All interfaces methods using AsyncResult<> have been marked @Deprecated
Implementation methods have been left as-s

callback-based methods are deprecated in vert.x 5

---

src/main/java/io/vertx/ext/mongo/MongoClient.java
src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java
src/test/java/io/vertx/ext/mongo/MongoClientTestBase.java

Motivation:
Add ability to drop index with keys json used to create it, no need to get keys from it.
Please check java driver document https://mongodb.github.io/mongo-java-driver/4.10/apidocs/mongodb-driver-reactivestreams/com/mongodb/reactivestreams/client/MongoCollection.html#dropIndex(org.bson.conversions.Bson) and mongodb document https://www.mongodb.com/docs/manual/reference/method/db.collection.dropIndex/

Add feature to drop index with keys json used to create it

---

src/main/java/io/vertx/ext/mongo/MongoClientBulkWriteResult.java
src/main/java/io/vertx/ext/mongo/impl/Utils.java
src/test/java/io/vertx/ext/mongo/MongoClientBulkWriteResultTest.java
src/test/java/io/vertx/ext/mongo/impl/UtilsTest.java

This pull request is created as fix for https://github.com/vert-x3/vertx-mongo-client/issues/284

Add inserted ids in bulk write response

---

src/main/java/io/vertx/ext/mongo/FindOptions.java

Motivation:
Correct Javadoc for variable DEFAULT_BATCH_SIZE.
Conformance:
Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

fix(javadoc): Fix documentation for default batchSize value

---

src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java
src/test/java/io/vertx/ext/mongo/MongoClientWithObjectIdTest.java
src/test/java/io/vertx/ext/mongo/MongoTestBase.java

Motivation:
If we give a query when "_id" field in a nested value like:
```json
{
"$and":[
{
"_id":"an-id-field"
},
{
"some":"other"
}
]
}
```
then, the nested "_id" will not be encoded.
I added a deep version of this method for handling this, we should only need this in query or filter.
Please review this @tsegismont @vietj 👀 If this logic is acceptable, I will complete the test cases, thanks!

Deep handle mongo ID_FIELD when useObjectId

---

src/main/java/io/vertx/ext/mongo/impl/config/MongoClientOptionsParser.java

Primary goal is to reduce the number of threads used, reusing the Netty event loop group of Vert.x

Switch to Netty transport instead of NIO
