vert-x3/vertx-mongo-client

vertx-mongo-client/src/main/asciidoc/groovy/index.adoc, vertx-mongo-client/src/main/asciidoc/java/index.adoc, vertx-mongo-client/src/main/asciidoc/js/index.adoc, vertx-mongo-client/src/main/asciidoc/ruby/index.adoc, vertx-mongo-client/src/main/java/examples/Examples.java, vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/codec/json/JsonObjectCodec.java, vertx-mongo-client/src/main/java/io/vertx/ext/mongo/package-info.java, vertx-mongo-client/src/test/java/io/vertx/ext/mongo/MongoClientTestBase.java, vertx-mongo-client/src/test/java/io/vertx/ext/mongo/impl/codec/json/AbstractJsonCodecTest.java, vertx-mongo-client/src/test/java/io/vertx/ext/mongo/impl/codec/json/JsonObjectCodecTest.java
BSON date support (cf http://docs.mongodb.org/manual/reference/mongodb-extended-json)
Today you get an error when you try to save a document with a date
=> Date type support

vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/config/MongoClientOptionsParser.java
Configuring correct parameter at MongoClientSettings.Builder for heartbeatSocketSettings.
=> Configuring correct parameter at MongoClientSettings.Builder

vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java, vertx-mongo-client/src/test/java/io/vertx/ext/mongo/MongoClientTestBase.java
Fix for https://github.com/vert-x3/vertx-mongo-client/issues/52
=> Make sure result handlers are called on the invokers context 

vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/codec/json/JsonObjectCodec.java, vertx-mongo-client/src/test/java/io/vertx/ext/mongo/impl/codec/json/JsonObjectCodecTest.java
1. Added timestamp extended json support.
2. Added test for the timestamp extended json support. #51
=> Extended JSON Support for Timestamp

vertx-mongo-client/pom.xml
Reverts vert-x3/vertx-mongo-client#73 - The plugin is not yet release.
=> Revert "bnd config to generate OSGi manifest"

vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java, vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/config/CredentialListParser.java, vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/config/MongoClientOptionsParser.java, vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/config/ReadPreferenceParser.java, vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/config/WriteConcernParser.java, vertx-mongo-client/src/test/java/io/vertx/ext/mongo/impl/config/MongoClientOptionsParserTest.java, vertx-mongo-client/src/test/java/io/vertx/ext/mongo/impl/config/ReadPreferenceParserTest.java, vertx-mongo-client/src/test/java/io/vertx/ext/mongo/impl/config/WriteConcernParserTest.java
This is a small change to read database name, write concern and readPreference from *connection_string* if connection_string is presented.
=> Respect database, write concern and read preference in connection_string

vertx-mongo-client/src/main/asciidoc/java/index.adoc
Change remove->removeDocuments, removeOne->removeDocument
Because remove & removeOne are deprecated
=> Update index.adoc (Java)

vertx-mongo-client/src/main/asciidoc/dataobjects.adoc, vertx-mongo-client/src/main/generated/io/vertx/rxjava/ext/mongo/MongoClient.java, vertx-mongo-client/src/main/groovy/io/vertx/groovy/ext/mongo/MongoClient.groovy, vertx-mongo-client/src/main/java/io/vertx/ext/mongo/FindOptions.java, vertx-mongo-client/src/main/java/io/vertx/ext/mongo/IndexOptions.java, vertx-mongo-client/src/main/java/io/vertx/ext/mongo/MongoClient.java, vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java, vertx-mongo-client/src/main/resources/vertx-mongo-js/mongo_client.js, vertx-mongo-client/src/main/resources/vertx-mongo/mongo_client.rb, vertx-mongo-client/src/test/java/io/vertx/ext/mongo/MongoClientTestBase.java, vertx-mongo-service/src/main/generated/io/vertx/ext/mongo/MongoServiceVertxEBProxy.java, vertx-mongo-service/src/main/generated/io/vertx/ext/mongo/MongoServiceVertxProxyHandler.java, vertx-mongo-service/src/main/generated/io/vertx/rxjava/ext/mongo/MongoService.java, vertx-mongo-service/src/main/groovy/io/vertx/groovy/ext/mongo/MongoService.groovy, vertx-mongo-service/src/main/java/io/vertx/ext/mongo/MongoService.java, vertx-mongo-service/src/main/java/io/vertx/ext/mongo/impl/MongoServiceImpl.java, vertx-mongo-service/src/main/resources/vertx-mongo-js/mongo_service.js, vertx-mongo-service/src/main/resources/vertx-mongo/mongo_service.rb
=> Indexes support

vertx-mongo-client/src/main/java/io/vertx/ext/mongo/package-info.java
See https://github.com/vert-x3/vertx-mongo-client/pull/92
=> Typo fix in the doc (fix PR #92 at source)

vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/config/ConnectionPoolSettingsParser.java
At line 39 in ConnectionsPoolSettings.java the maxWaitQueueSize is being set as waitQueueMultiple fixing that
=> fixing maxWaitQueueSize set by ConnectionPoolSettingsParser

vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java, vertx-mongo-client/src/test/java/io/vertx/ext/mongo/MongoClientWithObjectIdTest.java
Added converter to findOne to return string ID instead of $oid when useObjectId is true.
=> added convertCallback to findOne

vertx-mongo-client/src/main/java/examples/Examples.java, vertx-mongo-client/src/main/java/io/vertx/ext/mongo/MongoClient.java, vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java, vertx-mongo-client/src/main/java/io/vertx/ext/mongo/package-info.java, vertx-mongo-client/src/test/java/io/vertx/ext/mongo/DistinctTest.java
This is an enhancement over #50
Added two new methods to distinct with query
=> Distinct with query support

vertx-mongo-client/src/test/java/io/vertx/ext/mongo/MongoClientTestBase.java
The test currently fails because  `bulkResult.getMatchedCount()` returns 0 instead of 1.
=> Add test for bulkWrite replace using the '_id' property

src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java, src/test/java/io/vertx/ext/mongo/MongoClientTest.java
Fixes #149 
The ReadStream adapter for Observable makes sure handlers are set to null observable completes (required by some stream implementations).
This stream was over-defensive.
=> Allow MongoIterableStream handlers to be set to null after the stream is closed

src/main/asciidoc/dataobjects.adoc, src/main/generated/io/vertx/ext/mongo/AggregateOptionsConverter.java, src/main/java/io/vertx/ext/mongo/AggregateOptions.java, src/main/java/io/vertx/ext/mongo/MongoClient.java, src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java, src/test/java/io/vertx/ext/mongo/AggregateOptionsTest.java, src/test/java/io/vertx/ext/mongo/MongoClientTest.java
So here is the PR for vertx-mongo-client 3.6.0
https://github.com/vert-x3/vertx-mongo-client/pull/159
addressing https://github.com/vert-x3/vertx-mongo-client/issues/148
=> aggregate support for mongo 3.6

src/main/java/io/vertx/ext/mongo/MongoClient.java
inspired by https://github.com/vert-x3/vertx-lang-kotlin/issues/116 and https://github.com/vert-x3/vertx-redis-client/pull/116/files
=> Nullable async results

src/main/java/io/vertx/ext/mongo/UpdateOptions.java
Hello @karianna , I found misprint in UpdateOptions, and made a PR to fix it.
=> fix misprint in UpdateOptions, change multu to multi

src/main/java/io/vertx/ext/mongo/impl/codec/json/AbstractJsonCodec.java, src/main/java/io/vertx/ext/mongo/impl/codec/json/JsonObjectCodec.java, src/test/java/io/vertx/ext/mongo/impl/codec/json/JsonObjectCodecTest.java
Hello, @karianna , I made a PR for 103, what do you think about this solution?
=> support write Number Long resolve #103

src/main/asciidoc/dataobjects.adoc, src/main/java/io/vertx/ext/mongo/IndexModel.java, src/main/java/io/vertx/ext/mongo/MongoClient.java, src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java, src/test/java/io/vertx/ext/mongo/MongoClientTestBase.java
Hello, @karianna I added new method createIndexes it is referenced to #31, please review it. Thank you.
=> add createIndexes fix #31

src/main/asciidoc/index.adoc, src/main/java/io/vertx/ext/mongo/impl/config/SSLSettingsParser.java, src/test/java/io/vertx/ext/mongo/impl/config/ParsingSSLOptionsTest.java
PR to get #188 and #192 on 3.7
=> add trustAll and caPath for 3.7

src/main/asciidoc/index.adoc, src/main/java/io/vertx/ext/mongo/impl/config/SSLSettingsParser.java, src/test/java/io/vertx/ext/mongo/impl/config/ParsingSSLOptionsTest.java
=> Add additional warnings/doc to #188

src/main/java/io/vertx/ext/mongo/MongoClient.java
=> Determine and annotate mongo method that might return null so RxJava2 generates correct code

src/main/asciidoc/dataobjects.adoc, src/main/generated/io/vertx/ext/mongo/AggregateOptionsConverter.java, src/main/generated/io/vertx/ext/mongo/FindOptionsConverter.java, src/main/java/io/vertx/ext/mongo/UpdateOptions.java, src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java, src/test/java/io/vertx/ext/mongo/UpdateOptionsTest.java
enables queries like documented in then below link  
https://docs.mongodb.com/manual/reference/operator/update/positional-filtered
=> add arrayFilters in UpdateOptions

src/main/generated/io/vertx/ext/mongo/AggregateOptionsConverter.java, src/main/generated/io/vertx/ext/mongo/FindOptionsConverter.java, src/main/java/io/vertx/ext/mongo/impl/codec/json/AbstractJsonCodec.java, src/main/java/io/vertx/ext/mongo/impl/codec/json/JsonObjectCodec.java, src/test/java/io/vertx/ext/mongo/impl/codec/json/JsonObjectCodecTest.java
Link to issue https://github.com/vert-x3/vertx-mongo-client/issues/196
Support numberDecimal as string
Hello , please see it @karianna 
best wishes.
=> add support_number_decimal #196

src/main/java/io/vertx/ext/mongo/impl/MongoIterableStream.java, src/test/java/io/vertx/ext/mongo/MongoClientTest.java, src/test/java/io/vertx/ext/mongo/MongoClientTestBase.java, src/test/java/io/vertx/ext/mongo/MongoTestBase.java
same fix as for 3.8 but with prettier tests
fixes #183 #171
=> fix MongoIterableStream for 4.x

src/main/java/io/vertx/ext/mongo/MongoClient.java, src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java
Hello, @karianna, I added new way to configure mongo for jvm languages.
=> Add new_way of configure fix #208

src/main/java/io/vertx/ext/mongo/BulkOperation.java, src/main/java/io/vertx/ext/mongo/WriteOption.java
Add missing annotation on enums.
=> Add missing polyglot annotations

pom.xml, src/main/resources/META-INF/MANIFEST.MF
Signed-off-by: afloarea <adrianfloarea07@yahoo.com>
Motivation:
Add automatic module name as per [#524](https://github.com/vert-x3/issues/issues/524)
=> Add automatic module name via custom MANIFEST file

src/main/java/examples/MongoClientExamples.java
Use future composition in examples that are not single async method calls.
=> Futurized docs

src/main/java/io/vertx/ext/mongo/impl/codec/json/AbstractJsonCodec.java, src/test/java/io/vertx/ext/mongo/impl/codec/json/AbstractJsonCodecTest.java, src/test/java/io/vertx/ext/mongo/impl/codec/json/JsonObjectCodecTest.java
Motivation:
Fixes https://github.com/vert-x3/vertx-mongo-client/issues/244
may be related to https://github.com/vert-x3/vertx-mongo-client/issues/141 as well
I added as well a test to validate current Instance handling (gets converted to Bson String)
=> Fix Float handling

src/main/asciidoc/index.adoc, src/main/java/io/vertx/ext/mongo/impl/config/ClusterSettingsParser.java, src/main/java/io/vertx/ext/mongo/impl/config/ConnectionPoolSettingsParser.java, src/main/java/io/vertx/ext/mongo/impl/config/MongoClientOptionsParser.java, src/main/java/io/vertx/ext/mongo/impl/config/ReadConcernLevelParser.java, src/main/java/io/vertx/ext/mongo/impl/config/ReadPreferenceParser.java, src/main/java/io/vertx/ext/mongo/impl/config/SocketSettingsParser.java, src/main/java/io/vertx/ext/mongo/impl/config/WriteConcernParser.java, src/test/java/io/vertx/ext/mongo/impl/config/MongoClientOptionsParserTest.java, src/test/java/io/vertx/ext/mongo/impl/config/ParsingReadConcernLevelTest.java
Closes #243
This is a breaking change from configuration standpoint.
=> JSON config takes precedence over connection string

src/main/java/io/vertx/ext/mongo/MongoClient.java, src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java, src/test/java/io/vertx/ext/mongo/MongoClientTest.java
Motivation:
Add the support for watching MongoDB collection change stream.
=> Add Support of Mongo Collection Watch

src/main/java/io/vertx/ext/mongo/MongoClient.java, src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java, src/test/java/io/vertx/ext/mongo/MongoClientAggregateUpdateTest.java, src/test/java/io/vertx/ext/mongo/MongoTestBase.java
First proposal for issue/enhancement #236.
Second tentative since PR #251 has validation issues.
If successful, this PR replaces PR #251.
=> bump MongoDB version to 4.2.1 (#253) and added support for updates with aggregation pipelines (#236)

src/main/java/io/vertx/ext/mongo/impl/config/MongoClientOptionsParser.java
Motivation:
provide a way to set retryable settings
=> fix: low version of mongo not support retryWrites setting.

src/test/java/io/vertx/ext/mongo/MongoClientTest.java
Fixes #267
The test relied on a timer to make sure the watch was operational.
With this change, timing issues should be resolved.
=> Intermittent failures on MongoClientTest.testWatch

src/main/java/io/vertx/ext/mongo/impl/PublisherAdapter.java
Motivation:
This is a fix tentative of issue #286
To be honest, it should really be scrutinized by a Vert.x savvy person because those `ReadStream`, `Publisher`, `InboundBuffer`, `Channel` interactions are definitely beyond my grasp.
Unit tests are still passing, my program no longer fails with `OutOfMemoryError`, but still... at the end of my program, the capacity of the `InboundBuffer` (792)  is slightly above the specified `batchSize` (598). It is probably not a good omen.
I also noticed this part of `MongoClientImpl`:
```java
@Override
public ReadStream<JsonObject> findBatchWithOptions(String collection, JsonObject query, FindOptions options) {
requireNonNull(collection, COLLECTION_CANNOT_BE_NULL);
requireNonNull(query, QUERY_CANNOT_BE_NULL);
FindPublisher<JsonObject> view = …
```
=>  OutOfMemoryError when using toReceiveChannel on findBatchWithOptions or aggregate

pom.xml, src/main/java/io/vertx/ext/mongo/impl/PublisherAdapter.java, src/main/java/io/vertx/ext/mongo/impl/config/MongoClientOptionsParser.java
=> Mongo upgrade

src/main/java/io/vertx/ext/mongo/MongoGridFsClient.java, src/main/java/io/vertx/ext/mongo/impl/MongoGridFsClientImpl.java, src/test/java/io/vertx/ext/mongo/GridFsTest.java
Motivation:
Sometimes we need only a ReadStream, no need to write to a file.
=> Read file gridfs into ReadStream

pom.xml
=> Update commons-collections4 to version 4.4

pom.xml, src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java
=> Mongo Client should not require Jackson Databind

src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java, src/main/java/io/vertx/ext/mongo/impl/MongoGridFsClientImpl.java, src/test/java/io/vertx/ext/mongo/GridFsTest.java
=> Fix CodecConfigurationException on uploading nested metadata to GridFS

src/main/generated/io/vertx/ext/mongo/RenameCollectionOptionsConverter.java, src/main/java/io/vertx/ext/mongo/MongoClient.java, src/main/java/io/vertx/ext/mongo/RenameCollectionOptions.java, src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java, src/test/java/io/vertx/ext/mongo/MongoClientTestBase.java, src/test/java/io/vertx/ext/mongo/RenameCollectionOptionsTest.java
Motivation:
Apis and tests created for `renameCollection`, will solve #278
=> Add apis for rename collection

pom.xml
https://www.mongodb.com/community/forums/t/mongodb-java-driver-5-3-1-released/310986
=> Upgrade to Mongo Driver 5.3.1
